/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    primary: '#004DF5',
    secondary: '#2ecc71',
    error: '#e74c3c',
    warning: '#f39c12',
    success: '#2ecc71',
    info: '#3498db',
    darkC: '#000',
    transparent: 'transparent',
    blue: '#4267B2',
    red: '#D80000',
    green: '#2AC65F',
    white: '#FBFBFB',
    lightWhite: '#FFFFFF',
    lightBlue: '#6885C1',
    lightRed: '#EB9C9B',
    lightGreen: '#73ADA1',
    black: '#121212',
    dark: '#3D3A45',
    gray: '#8C8896',
    lightGrey: '#CACACA',
    lightBlack: '#292929',
    nagivationPrimary: '#2E2E2E',
    description: '#71727A',
    lightInput: '#F5F5F5',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    primary: '#D2FF53',
    secondary: '#27ae60',
    error: '#c0392b',
    warning: '#e67e22',
    success: '#27ae60',
    info: '#2980b9',
    transparent: 'transparent',
    blue: '#4267B2',
    red: '#D80000',
    green: '#2AC65F',
    white: '#FBFBFB',
    lightWhite: '#FFFFFF',
    lightBlue: '#6885C1',
    lightRed: '#EB9C9B',
    lightGreen: '#73ADA1',
    black: '#121212',
    dark: '#3D3A45',
    gray: '#8C8896',
    lightGrey: '#CACACA',
    lightBlack: '#292929',
    nagivationPrimary: '#2E2E2E',
    description: '#71727A',
    lightInput: '#F5F5F5',
  },
};
